export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const ADD_PLAYLIST_START = 'ADD_PLAYLIST_START';
export const ADD_PLAYLIST_SUCCESS = 'ADD_PLAYLIST_SUCCESS';
export const ADD_PLAYLIST_FAIL = 'ADD_PLAYLIST_FAIL';
export const ADDING_PLAYLIST_START = 'ADDING_PLAYLIST_START';
export const ADDING_PLAYLIST_END = 'ADDING_PLAYLIST_END';

export const DELETE_PLAYLIST_START = 'DELETE_PLAYLIST_START';
export const DELETE_PLAYLIST_SUCCESS = 'DELETE_PLAYLIST_SUCCESS';
export const DELETE_PLAYLIST_FAIL = 'DELETE_PLAYLIST_FAIL';
export const DELETING_PLAYLIST_START = 'DELETING_PLAYLIST_START';
export const DELETING_PLAYLIST_END = 'DELETING_PLAYLIST_END';

export const GET_PLAYLISTS_START = 'GET_PLAYLISTS_START';
export const GET_PLAYLISTS_SUCCESS = 'GET_PLAYLISTS_SUCCESS';
export const GET_PLAYLISTS_FAIL = 'GET_PLAYLISTS_FAIL';

export const ADD_FILES = 'ADD_FILES';
export const ADD_SONGS_START = 'ADD_SONGS_START';
export const ADD_SONGS_SUCCESS = 'ADD_SONGS_SUCCESS';
export const ADD_SONGS_FAIL = 'ADD_SONGS_FAIL';
export const ADDING_SONGS_START = 'ADDING_SONGS_START';
export const ADDING_SONGS_END = 'ADDING_SONGS_END';

export const DELETE_SONG_START = 'DELETE_SONG_START';
export const DELETE_SONG_SUCCESS = 'DELETE_SONG_SUCCESS';
export const DELETE_SONGS_FAIL = 'DELETE_SONGS_FAIL';
export const DELETING_SONG_START = 'DELETING_SONG_START';
export const DELETING_SONG_END = 'DELETING_SONG_END';
export const SET_SONGS_AFTER_DELETE = 'SET_SONGS_AFTER_DELETE'; 


export const SET_SONGS = 'SET_SONGS'; 
export const SET_PLAYING_ORDER = 'SET_PLAYING_ORDER'; 
export const RESET_PLAYING = 'RESET_PLAYING'; 
export const PLAY_SONG = 'PLAY_SONG';

